### ISSUE TITLE
智能家居技能调试时出现sdk崩溃

### ISSUE THREAD

**Issue by zhang6321615** [dueros/bot-sdk-node.js#5]
新建立一个智能家居技能选项，用模拟测试 发送 “发现设备” 即可出现如下崩溃信息。

错误信息：
～/duer-node/node_modules/bot-sdk/lib/Session.js:35
        let attributes = data.attributes;
                             ^

TypeError: Cannot read property 'attributes' of undefined
    at new Session (/home/live/duer-node/node_modules/bot-sdk/lib/Session.js:35:30)
    at new Request (/home/live/duer-node/node_modules/bot-sdk/lib/Request.js:40:25)
    at Bot (/home/live/duer-node/node_modules/bot-sdk/lib/Bot.js:54:24)
    at Bot (/home/live/duer-node/bot.js:10:9)
    at IncomingMessage.<anonymous> (/home/live/duer-node/app.js:24:17)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

SDK版本：
    "bot-sdk": "^1.1.1"

**Comment by zhang6321615** [comment]
这个问题已经跟百度方面确认了。 引发崩溃是因为 该SDK不兼容 智能家居协议. 
这个SDK主要是针对  普通技能使用。 望大家看到后相互转告。。
