### ISSUE TITLE
TypeError: BodyTemplate5 is not a constructor

### ISSUE THREAD

**Issue by zlcnup** [dueros/bot-sdk-node.js#8]
TypeError: BodyTemplate5 is not a constructor
at _intentHandler.set (/zl/msites/zl/node_modules/bot-sdk/lib/Bot.js:128:28)
at Bot._intentDispatch (/node_modules/bot-sdk/lib/Bot.js:454:56)
at Bot._run (/node_modules/bot-sdk/lib/Bot.js:424:24)
at /zl/msites/zl/node_modules/bot-sdk/lib/Bot.js:386:30
at <anonymous>

**Comment by zlcnup** [comment]
OK. This is the error in README.md. I copy the code from README.md. Many examples have no `BaseBot.Directive.Display.[Template].BodyTemplate5;`
